server:
  port: 8080

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: catalogServiceRoute
            uri: lb://catalog-service/
            predicates:
            - Path=/catalog/**
          - id: moviesRoute
            uri: lb://movie-service/
            predicates:
              - Path=/movie/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
